---
- hosts: all
  vars:
   app_dir: /var/www/myapp
   repo_url: https://github.com/cyebr007/ansible.git
  tasks:
  - name: Ensure Git is installed
    apt:
     name: git
     state: present
    become: yes

  - name: Clone application repo
    git:
     repo: "{{ repo_url }}"
     dest: "{{ app_dir }}"
     clone: yes
     update: yes
    become: yes

  - name: Ensure pip is installed
    apt:
     name: python3-pip
     state: present
    become: yes

  - name: Install application requirements
    pip:
     requirements: "{{ app_dir }}"/requirements.txt"
     executable: pip3
    become: yes

  - name: Restart the application
    systemd:
     name: myapp
     state: restricted
    become: yes
...